name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Get Date
      run: |
        $date = Get-Date -Format "yyyy-MM-dd"
        echo "ISODATE=$date" >> $env:GITHUB_ENV
        
    - run: echo "VERSION=8.7.1-nightly.${{env.ISODATE}}" >> $env:GITHUB_ENV
    
    # tag this commit
    - name: Create Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false
        custom_tag: ${{ env.VERSION }}
        tag_prefix: ""
        dry_run: true

    # echo
    - name: output step
      run: |
        echo new_tag ${{ steps.tag_version.outputs.new_tag }} \n new_version ${{ steps.tag_version.outputs.new_version }} \n previous_tag ${{ steps.tag_version.outputs.previous_tag }} \n previous_version ${{ steps.tag_version.outputs.previous_version }}  \n previous_version ${{ steps.tag_version.outputs.previous_version }}
    # echo
    - name: output step
      run: |
        echo 
        new_tag ${{ steps.tag_version.outputs.new_tag }}
        new_version ${{ steps.tag_version.outputs.new_version }}
        previous_tag ${{ steps.tag_version.outputs.previous_tag }}
        previous_version ${{ steps.tag_version.outputs.previous_version }}
        previous_version ${{ steps.tag_version.outputs.previous_version }}


    # echo
    - name: output
      run: |
        echo "This is a beta release so you may encounter bugs. Please report them. \n ${{ steps.tag_version.outputs.changelog }}"
